apiVersion: v1
kind: Pod
metadata:
  name: pytorch-example
spec:
  containers:
  - name: gpu-container
    image: gcr.io/pytorch/pytorch
    imagePullPolicy: Always
    args: ["sleep", "36500000"]
    resources:
      limits:
        nvidia.com/gpu: 1
    volumeMounts:
    - mountPath: /examples
      name: pytorch-examples
  volumes:
    - name: pytorch-examples
      gitRepo:
        repository: "https://github.com/Hvass-Labs/TensorFlow-Tutorials"